# Author: Logan Simonis

numOne = input("Number: ")
numTwo = input("Another Number: ")
liquid = input("Liquid: ")
animal = input("Animal: ")
numThree = input("Another Number: ")
firstAdj = input("Adjective: ")
sweetFood = input("Sweet Food: ")
numFour = input("Another Number: ")
secondAdj = input("Another Adjective: ")
print("")
print("**Mom's Famouse Receipe!**")
print("")
print(f"First, preheat the oven to {numOne} degrees. Then beat {numTwo} {animal} egg(s) with a cup of {liquid}.")
print(f"Next add {numThree} teaspoon(s) of baking soda and mix with eggs and {liquid} until it reaches a {firstAdj} texture.")
print(f"Don't forget the {sweetFood}! Pour into a 9 by 9 pan and bake for {numFour} minute(s) or until the cake is {secondAdj}.")